// frontend/src/components/molecules/ComparatorActions.svelte
<script lang="ts">
  import Button from '../atoms/Button.svelte';

  interface Props {
    onSwap?: () => void;
    onClear?: () => void;
    swapLabel?: string;
    clearLabel?: string;
  }

  let { onSwap, onClear, swapLabel = 'Swap Items', clearLabel = 'Clear All' }: Props = $props();
</script>

<div class="flex gap-3">
  <Button onClick={onSwap} variant="primary">{swapLabel}</Button>
  <Button onClick={onClear} variant="secondary">{clearLabel}</Button>
</div>

// frontend/src/components/molecules/ComparatorActions.tsx
import React from "react";
import { Button, Icon } from "../atoms";

interface ComparatorActionsProps {
  onSwap: () => void;
  onClear: () => void;
  hasItems: boolean;
}

export function ComparatorActions({
  onSwap,
  onClear,
  hasItems,
}: ComparatorActionsProps) {
  return (
    <div className="flex gap-3 justify-center flex-wrap">
      <Button
        variant="secondary"
        onClick={onSwap}
        disabled={!hasItems}
        title="Swap items between slots"
        className="gap-2"
      >
        <Icon name="swap" size={18} />
        <span>Swap Items</span>
      </Button>

      <Button
        variant="destructive"
        onClick={onClear}
        disabled={!hasItems}
        title="Clear comparison"
        className="gap-2"
      >
        <Icon name="x" size={18} />
        <span>Clear</span>
      </Button>
    </div>
  );
}
