// frontend/src/components/atoms/Badge.tsx
import React from "react";
import { ItemRarity } from "../../types";
import { cn } from "../../utils/cn";

interface BadgeProps {
  variant?: ItemRarity | "default";
  children: React.ReactNode;
  className?: string;
}

const rarityBgColors: Record<ItemRarity | "default", string> = {
  common: "bg-muted",
  magic: "bg-blue-600/80",
  rare: "bg-yellow-600/80",
  unique: "bg-orange-600/80",
  default: "bg-muted",
};

const rarityTextColors: Record<ItemRarity | "default", string> = {
  common: "text-muted-foreground",
  magic: "text-blue-100",
  rare: "text-yellow-100",
  unique: "text-orange-100",
  default: "text-muted-foreground",
};

export function Badge({
  variant = "default",
  children,
  className,
}: BadgeProps) {
  return (
    <span
      className={cn(
        "inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium",
        rarityBgColors[variant],
        rarityTextColors[variant],
        className
      )}
    >
      {children}
    </span>
  );
}

// frontend/src/components/atoms/Badge.svelte
<script lang="ts">
  interface Props {
    rarity?: 'common' | 'magic' | 'rare' | 'unique' | 'currency';
    className?: string;
  }

  const rarityClasses: Record<NonNullable<Props['rarity']>, string> = {
    common: 'bg-muted text-foreground',
    magic: 'bg-blue-500/20 text-blue-300',
    rare: 'bg-yellow-500/20 text-yellow-300',
    unique: 'bg-orange-500/20 text-orange-300',
    currency: 'bg-emerald-500/20 text-emerald-300'
  };

  let { rarity = 'common', className = '', children }: Props & { children: any } = $props();
</script>

<span class={`inline-flex rounded px-2 py-0.5 text-xs font-medium uppercase ${rarityClasses[rarity]} ${className}`.trim()}>
  {@render children?.()}
</span>
